spring:
  profiles:
    active: "development"
---
spring:
  config:
    activate:
      on-profile: "development"
  jpa:
    hibernate:
      ddl-auto: validate
    #      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
    show-sql: true
  datasource:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/deal
    username: deal
    password: dealdeal
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog.xml
server:
  port: 8081
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

---
spring:
  config:
    activate:
      on-profile: "production"





