spring:
  profiles:
    active: "development"
---
spring:
  config:
    activate:
      on-profile: "development"
  application:
    name: statement
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
statement:
    dealUrl: http://deal:8080
