services:
  postgres:
    image: postgres:15.5
    environment:
      POSTGRES_DB: "deal"
      POSTGRES_USER: "deal"
      POSTGRES_PASSWORD: "dealdeal"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5433:5432"