spring:
  profiles:
    active: "development"
---
spring:
  config:
    activate:
      on-profile: "development"
  application:
    name: dossier
  mail:
    host: smtp.gmail.com
    port: 587
    username: NAME
    password: PASS
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
  kafka:
    bootstrap-servers:
    - localhost:9092
    consumer:
      group-id: dossier
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

server:
  port: 8083
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
dossier:
  dealUrl: http://127.0.0.1:8081