spring:
  profiles:
    active: "development"
---
spring:
  config:
    activate:
      on-profile: "development"
  application:
    name: dossier
server:
  port: 8083
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
