name: codecov

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 1.11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Maven verify
        run: cd ./calculator/ && mvn -B clean verify

      - name: Build deal with Maven
        run: cd ./deal/ && mvn -B clean verify

      - name: Build statement with Maven
        run: cd ./statement/ && mvn -B clean verify

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}