name: credit-bank-application with Maven

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build calculator with Maven
        run: cd ./calculator/ && mvn -B clean package dockerfile:build

      - name: Build deal with Maven
        run: cd ./deal/ && mvn -B clean package dockerfile:build

      - name: Build dossier with Maven
        run: cd ./dossier/ && mvn -B clean package dockerfile:build

      - name: Build gateway with Maven
        run: cd ./gateway/ && mvn -B clean package dockerfile:build

      - name: Build statement with Maven
        run: cd ./statement/ && mvn -B clean package dockerfile:build